name: Package & Upload to PyPI

on:
  push:
    branches: [master]
    
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1.1.1
        with:
          python-version: 3.8

      - name: Install requirements
        run: |
          sudo pip install setuptools && \
          sudo pip install credstash twine && \
          sudo pip install -r requirements.txt -r requirements_dev.txt

      - name: Build sdist tarball
        run: python setup.py bdist_wheel

      - name: Fetch secrets
        id: secrets
        run: |
          # failures in the set-env command don't cause the workflow to fail.
          # calling this and then running set-env should flag up errors
          echo "::set-env name=PYPI_TOKEN::$(credstash get pypi-keymaster-token)"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CREDSTASH_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CREDSTASH_SECRET_KEY }}
          AWS_DEFAULT_REGION: ca-central-1

      - name: Push wheel to pypi
        run: twine upload -u '__token__' -p "$PYPI_TOKEN" dist/*
